name: CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22-alpine
    env:
      PERSON1: ${{ secrets.PERSON1  }}
      PERSON2: ${{ secrets.PERSON2  }}
      PERSON3: ${{ secrets.PERSON3  }}
      PERSON4: ${{ secrets.PERSON4  }}
      PERSON5: ${{ secrets.PERSON5  }}
      PERSON6: ${{ secrets.PERSON6  }}
      PERSON7: ${{ secrets.PERSON7  }}
      PERSON8: ${{ secrets.PERSON8  }}
      JWT_SECRET: test-secret-key
      ATLAS_URI: mongodb://test-db
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm install
      - run: npm ci
      - run: npm run test
      - run: npm run build
